import { useEffect, useRef } from 'react';
import { useForm, Controller, useFieldArray } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';

import { Input } from '../../components/ui/input';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '../../components/ui/select';
import { Button } from '../../components/ui/button';
import { useConfigurationStore, useValidationStore } from "@/store/useConfigurationStore.ts";
import { ConfigTabSection } from './components/ConfigTabSection.tsx';
import { FieldLabel } from '../../components/ui/FieldLabel.tsx';
import { compileZodErrors } from "./utils/validationUtils.ts";
import { daqSchema } from "./profileSchemas/daqSchema.ts";
import { DAQProfileCard } from "./components/DAQProfileCard.tsx";
import { useFormAutoSave } from "./hooks/useFormAutoSave.ts";
import { tooltips } from "@/config/tooltips.ts";
import { Plus } from 'lucide-react';

export const TabDAQ = () => {
    const { draft, updateDraft, lastLoadedPath } = useConfigurationStore();
    const loadedPathRef = useRef<string>("");

    const {
        register,
        control,
        watch,
        reset,
        setValue,
        formState: { errors },
    } = useForm<z.infer<typeof daqSchema>>({
        resolver: zodResolver(daqSchema),
        mode: "onChange",
        defaultValues: {
            requiredAxes: draft.requiredAxes || ["A", "B", "RA", "RB"],
            daqFrequency: draft.daqFrequency,
            samplePoints: draft.samplePoints,
            handlersProfile: (draft.handlerProfiles || []).map(profile => {
                const rawAi = profile.verboseAi || "";
                return {
                    ...profile,
                    verboseAxis: profile.verboseAxis || "-1",
                    verboseTask: profile.verboseTask || "-1",
                    verboseSystem: profile.verboseSystem ?? -1,
                    verboseIO: profile.verboseIO ?? -1,
                    loadA: rawAi.includes("LoadA"),
                    strain: rawAi.includes("Strain"),
                    specLoadFrameComm: rawAi.includes("SpecComm"),
                    cycles: profile.cycles || [],
                };
            }),
        },
    });

    // Re-initialize form defaultValues when a new file is loaded from the gateway
    useEffect(() => {
        if (lastLoadedPath && lastLoadedPath !== loadedPathRef.current) {
            loadedPathRef.current = lastLoadedPath;
            reset({
                requiredAxes: draft.requiredAxes || ["A", "B", "RA", "RB"],
                daqFrequency: draft.daqFrequency,
                samplePoints: draft.samplePoints,
                handlersProfile: (draft.handlerProfiles || []).map(profile => {
                    const rawAi = profile.verboseAi || "";
                    return {
                        ...profile,
                        verboseAxis: profile.verboseAxis || "-1",
                        verboseTask: profile.verboseTask || "-1",
                        verboseSystem: profile.verboseSystem ?? -1,
                        verboseIO: profile.verboseIO ?? -1,
                        loadA: rawAi.includes("LoadA"),
                        strain: rawAi.includes("Strain"),
                        specLoadFrameComm: rawAi.includes("SpecComm"),
                        cycles: profile.cycles || [],
                    };
                }),
            });
        }
    }, [lastLoadedPath, reset, draft]);

    const {
        fields,
        prepend,
        remove
    } = useFieldArray({
        control,
        name: "handlersProfile",
    });

    const watchedValues = watch();

    // Auto-generate filenames based on mode, sample, experiment, and index
    useEffect(() => {
        const sample = draft.sampleName || "";
        const exp = draft.experimentNumber || "";
        const totalCount = watchedValues.handlersProfile?.length || 0;
        watchedValues.handlersProfile?.forEach((profile: any, idx: number) => {
            const daqType = profile.mode === 'time-series' 
                ? 'timeseries' 
                : (profile.mode === 'peak-valley' ? 'peakvalley' : 'pso');
            
            const expectedName = `${daqType}_${sample.trim()}_${exp.trim()}-${totalCount - idx}`;
            
            // Only auto-generate/update if filename is empty, or matches the default pattern of any mode
            const isAutoGenerated = !profile.filename || 
                /^(timeseries|peakvalley|pso)_.*-\d+$/.test(profile.filename);
            
            if (isAutoGenerated && profile.filename !== expectedName) {
                setValue(`handlersProfile.${idx}.filename`, expectedName, { shouldDirty: true });
            }
        });
    }, [watchedValues.handlersProfile?.map((p: any) => p.mode).join(','), watchedValues.handlersProfile?.length, draft.sampleName, draft.experimentNumber, setValue]);

    // Map errors to the global validation errors list dynamically by validating watchedValues against Zod schema
    const { setErrors } = useValidationStore();
    useEffect(() => {
        const mappedProfiles = (watchedValues.handlersProfile || []).map((profile: any) => {
            const aiArray: string[] = [];
            if (profile.loadA) aiArray.push("LoadA");
            if (profile.strain) aiArray.push("Strain");
            if (profile.specLoadFrameComm) aiArray.push("SpecComm");
            
            return {
                mode: profile.mode,
                filename: profile.filename,
                verboseAxis: profile.verboseAxis,
                verboseTask: profile.verboseTask,
                verboseSystem: profile.verboseSystem,
                verboseIO: profile.verboseIO,
                verboseAi: aiArray.join(", "),
                frequency: profile.frequency,
                cycles: profile.cycles,
                signalAxis: profile.signalAxis,
                signalItem: profile.signalItem,
                signalProminence: profile.signalProminence,
                psoAxis: profile.psoAxis,
                signalLoad: profile.signalLoad,
                signalStrain: profile.signalStrain,
            };
        });

        const validationPayload = {
            requiredAxes: watchedValues.requiredAxes,
            daqFrequency: watchedValues.daqFrequency,
            samplePoints: watchedValues.samplePoints,
            handlersProfile: mappedProfiles
        };

        const result = daqSchema.safeParse(validationPayload);
        if (!result.success) {
            const errorMessages = compileZodErrors(result.error);
            
            const existingErrors = useValidationStore.getState().errors['daq'] || [];
            const hasChanged = 
                existingErrors.length !== errorMessages.length ||
                errorMessages.some((msg, idx) => msg !== existingErrors[idx]);
            
            if (hasChanged) {
                setErrors('daq', errorMessages);
            }
        } else {
            const existingErrors = useValidationStore.getState().errors['daq'] || [];
            if (existingErrors.length > 0) {
                setErrors('daq', []);
            }
        }
    }, [watchedValues, setErrors]);

    // Sync form values to the store draft on every change — including partial/invalid state
    useFormAutoSave({
        watchedValues,
        storeDraft: draft,
        updateDraft,
        mapValues: (watched) => {
            const mappedProfiles = (watched.handlersProfile || []).map((profile: any) => {
                const aiArray: string[] = [];
                if (profile.loadA) aiArray.push("LoadA");
                if (profile.strain) aiArray.push("Strain");
                if (profile.specLoadFrameComm) aiArray.push("SpecComm");
                
                return {
                    mode: profile.mode,
                    filename: profile.filename,
                    verboseAxis: profile.verboseAxis,
                    verboseTask: profile.verboseTask,
                    verboseSystem: profile.verboseSystem,
                    verboseIO: profile.verboseIO,
                    verboseAi: aiArray.join(", "),
                    frequency: profile.frequency,
                    cycles: profile.cycles,
                    signalAxis: profile.signalAxis,
                    signalItem: profile.signalItem,
                    signalProminence: profile.signalProminence,
                    psoAxis: profile.psoAxis,
                    signalLoad: profile.signalLoad,
                    signalStrain: profile.signalStrain,
                };
            });

            return {
                requiredAxes: watched.requiredAxes,
                daqFrequency: watched.daqFrequency,
                samplePoints: watched.samplePoints,
                handlerProfiles: mappedProfiles
            };
        }
    });

    return (
        <ConfigTabSection
            title="Data Acquisition Configuration"
            titleTooltip={tooltips.daqSectionTitle}
            description="Configure parameters for Data Acquisition."
            profilesTitle="DAQ Handler Profiles"
            profilesTitleTooltip={tooltips.daqProfilesHeader}
            profilesAction={
                <Button 
                    type="button" 
                    onClick={() => prepend({ 
                        mode: "time-series", 
                        filename: "",
                        verboseAxis: "-1",
                        verboseSystem: -1,
                        verboseTask: "-1",
                        verboseIO: -1,
                        verboseAi: "",
                        loadA: false,
                        strain: false,
                        specLoadFrameComm: false,
                        frequency: 1000,
                        cycles: [],
                        signalAxis: "A",
                        signalItem: "PositionFeedback",
                        signalProminence: null,
                        psoAxis: "A"
                    })}
                    className="h-8 px-4 text-xs font-semibold rounded-lg bg-mauve-600 hover:bg-mauve-700 text-white flex items-center gap-1.5 cursor-pointer shadow-sm animate-fade-in"
                >
                    <Plus className="h-3.5 w-3.5" /> Add Handler Profile
                </Button>
            }
            profiles={
                <div className="w-full space-y-6 pb-12">
                    {/* Render handler profile cards */}
                    {fields.map((field, index) => (
                        <DAQProfileCard
                            key={field.id}
                            index={index}
                            control={control}
                            register={register}
                            errors={errors}
                            remove={remove}
                            currentMode={watch(`handlersProfile.${index}.mode`)}
                            requiredAxes={watch("requiredAxes") || draft.requiredAxes || ["A", "B", "RA", "RB"]}
                        />
                    ))}
                </div>
            }
        >
            {/* Global Data Acquisition Settings */}
            <div className="col-span-2 flex flex-col gap-6 border-b border-mauve-250/30 pb-6 mb-2">
                <h4 className="text-md font-bold text-mauve-850">Global Data Acquisition Settings</h4>
                
                <div className="grid grid-cols-1 md:grid-cols-2 gap-x-12 gap-y-6 text-left">
                    {/* Sampling Frequency Field */}
                    <div className="flex flex-col gap-2">
                        <FieldLabel text="Sampling Frequency" tooltip={tooltips.daqFrequency} required={true} />
                        <Controller
                            control={control}
                            name="daqFrequency"
                            render={({ field }) => (
                                <Select 
                                    onValueChange={(val) => field.onChange(Number(val))} 
                                    value={field.value ? String(field.value) : undefined}
                                >
                                    <SelectTrigger className="bg-white border-mauve-200 h-9 w-full">
                                        <SelectValue placeholder="Select frequency" />
                                    </SelectTrigger>
                                    <SelectContent className="bg-white">
                                        <SelectItem value="1" className="text-xs cursor-pointer">1 kHz</SelectItem>
                                        <SelectItem value="5" className="text-xs cursor-pointer">5 kHz</SelectItem>
                                        <SelectItem value="10" className="text-xs cursor-pointer">10 kHz</SelectItem>
                                        <SelectItem value="20" className="text-xs cursor-pointer">20 kHz</SelectItem>
                                    </SelectContent>
                                </Select>
                            )}
                        />
                        {errors.daqFrequency && (
                            <p className="text-xs text-destructive">{errors.daqFrequency.message}</p>
                        )}
                    </div>

                    {/* Sample Points Field */}
                    <div className="flex flex-col gap-2">
                        <FieldLabel text="Sample Points" tooltip={tooltips.samplePoints} required={true} />
                        <Input 
                            type="number" 
                            placeholder="Enter points (min 100)" 
                            className="bg-white border-mauve-250 focus-visible:ring-mauve-300 h-9"
                            {...register('samplePoints', { valueAsNumber: true })}
                        />
                        {errors.samplePoints && (
                            <p className="text-xs text-destructive">{errors.samplePoints.message}</p>
                        )}
                    </div>
                </div>
            </div>
        </ConfigTabSection>
    );
}
